// <auto-generated />
using System;
using GPMS.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPMS.Backend.Data.Migrations
{
    [DbContext(typeof(GPMSDbContext))]
    [Migration("20240712055856_InitialGPMS")]
    partial class InitialGPMS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionEstimation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Batch")
                        .HasColumnType("int");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductionRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionRequirementId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Quarter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionRequirementId");

                    b.HasIndex("ProductionRequirementId1");

                    b.ToTable("ProductionEstimation");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 895, DateTimeKind.Utc).AddTicks(8354));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentProductionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentProductionPlanId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("ParentProductionPlanId");

                    b.HasIndex("ParentProductionPlanId1");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffId1");

                    b.ToTable("ProductionPlan");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Batch")
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionPlanId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Quarter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductSpecificationId");

                    b.HasIndex("ProductSpecificationId1");

                    b.HasIndex("ProductionPlanId");

                    b.HasIndex("ProductionPlanId1");

                    b.ToTable("ProductionRequirement");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CurrentProcess")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FaultyQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductionEstimationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionEstimationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductionEstimationId");

                    b.HasIndex("ProductionEstimationId1");

                    b.ToTable("ProductionSeries");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConsumptionUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SizeWidthUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Material");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 873, DateTimeKind.Utc).AddTicks(9354));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURLs")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffId1");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductProductionProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductProductionProcess");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<float>("OutputPerHour")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductionProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("StandardTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductionProcessId");

                    b.HasIndex("ProductionProcessId1");

                    b.ToTable("ProductionProcessStep");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStepIO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Consumption")
                        .HasColumnType("real");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaterialId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessStepId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("SemiFinishedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SemiFinishedProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialId1");

                    b.HasIndex("ProductionProcessStepId");

                    b.HasIndex("ProductionProcessStepId1");

                    b.HasIndex("SemiFinishedProductId");

                    b.HasIndex("SemiFinishedProductId1");

                    b.ToTable("ProductionProcessStepIO");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.SemiFinishedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("SemiFinishedProduct");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.BillOfMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Consumption")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SizeWidth")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialId1");

                    b.HasIndex("ProductSpecificationId");

                    b.HasIndex("ProductSpecificationId1");

                    b.ToTable("BillOfMaterial");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Measure")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductSpecificationId");

                    b.HasIndex("ProductSpecificationId1");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehouseId1");

                    b.ToTable("ProductSpecification");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.QualityStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaterialId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialId1");

                    b.HasIndex("ProductSpecificationId");

                    b.HasIndex("ProductSpecificationId1");

                    b.ToTable("QualityStandard");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.InspectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 844, DateTimeKind.Utc).AddTicks(7733));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductionSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionSeriesId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ProductionSeriesId");

                    b.HasIndex("ProductionSeriesId1");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffId1");

                    b.ToTable("InspectionRequest");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.WarehouseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 986, DateTimeKind.Utc).AddTicks(4178));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductionRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionRequirementId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewerId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorId1");

                    b.HasIndex("ProductionRequirementId");

                    b.HasIndex("ProductionRequirementId1");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ReviewerId1");

                    b.ToTable("WarehouseRequest");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.FaultyProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 837, DateTimeKind.Utc).AddTicks(4557));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InspectionRequestResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InspectionRequestResultId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductOrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRequestResultId");

                    b.HasIndex("InspectionRequestResultId1");

                    b.HasIndex("SpecificationId");

                    b.HasIndex("SpecificationId1");

                    b.ToTable("FaultyProduct");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.InspectionRequestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 854, DateTimeKind.Utc).AddTicks(4597));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FaultyQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("InspectionRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InspectionRequestId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorId1");

                    b.HasIndex("InspectionRequestId")
                        .IsUnique();

                    b.HasIndex("InspectionRequestId1")
                        .IsUnique();

                    b.ToTable("InspectionRequestResult");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductFault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FaultyProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaultyProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductMeasurementId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessStepId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QualityStandardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QualityStandardId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FaultyProductId");

                    b.HasIndex("FaultyProductId1");

                    b.HasIndex("ProductMeasurementId")
                        .IsUnique()
                        .HasFilter("[ProductMeasurementId] IS NOT NULL");

                    b.HasIndex("ProductMeasurementId1");

                    b.HasIndex("ProductionProcessStepId");

                    b.HasIndex("ProductionProcessStepId1");

                    b.HasIndex("QualityStandardId");

                    b.HasIndex("QualityStandardId1");

                    b.ToTable("ProductFault");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductionProcessStepIOResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Consumption")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductionProcessStepIOId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionProcessStepResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StepIOId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductionProcessStepIOId");

                    b.HasIndex("ProductionProcessStepResultId");

                    b.HasIndex("StepIOId");

                    b.HasIndex("StepResultId");

                    b.ToTable("ProductionProcessStepIOResult");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 920, DateTimeKind.Utc).AddTicks(1264));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("InspectionRequestResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InspectionRequestResultId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionSeriesId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorId1");

                    b.HasIndex("InspectionRequestResultId")
                        .IsUnique()
                        .HasFilter("[InspectionRequestResultId] IS NOT NULL");

                    b.HasIndex("InspectionRequestResultId1")
                        .IsUnique()
                        .HasFilter("[InspectionRequestResultId1] IS NOT NULL");

                    b.HasIndex("ProductionSeriesId");

                    b.HasIndex("ProductionSeriesId1");

                    b.ToTable("ProductionProcessStepResult");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 55, 820, DateTimeKind.Utc).AddTicks(2023));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("AccountId1");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Warehouses.WarehouseTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 12, 5, 58, 56, 0, DateTimeKind.Utc).AddTicks(547));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProductSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WarehouseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WarehouseRequestId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductSpecificationId");

                    b.HasIndex("ProductSpecificationId1");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehouseId1");

                    b.HasIndex("WarehouseRequestId")
                        .IsUnique()
                        .HasFilter("[WarehouseRequestId] IS NOT NULL");

                    b.HasIndex("WarehouseRequestId1");

                    b.ToTable("WarehouseTicket");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionEstimation", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", null)
                        .WithMany()
                        .HasForeignKey("ProductionRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", "ProductionRequirement")
                        .WithMany("ProductionEstimations")
                        .HasForeignKey("ProductionRequirementId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionRequirement");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", null)
                        .WithMany()
                        .HasForeignKey("ParentProductionPlanId");

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", "ParentProductionPlan")
                        .WithMany("ChildProductionPlans")
                        .HasForeignKey("ParentProductionPlanId1");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("CreatedProductionPlans")
                        .HasForeignKey("StaffId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("ReviewedProductionPlans")
                        .HasForeignKey("StaffId1");

                    b.Navigation("Creator");

                    b.Navigation("ParentProductionPlan");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "ProductSpecification")
                        .WithMany("ProductionRequirements")
                        .HasForeignKey("ProductSpecificationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", null)
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", "ProductionPlan")
                        .WithMany("ProductionRequirements")
                        .HasForeignKey("ProductionPlanId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSpecification");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionEstimation", null)
                        .WithMany()
                        .HasForeignKey("ProductionEstimationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionEstimation", "ProductionEstimation")
                        .WithMany("ProductionSeries")
                        .HasForeignKey("ProductionEstimationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionEstimation");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Product", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("CreatedProducts")
                        .HasForeignKey("StaffId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("ReviewedProducts")
                        .HasForeignKey("StaffId1");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductProductionProcess", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", "Product")
                        .WithMany("ProductionProcesses")
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductProductionProcess", null)
                        .WithMany()
                        .HasForeignKey("ProductionProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductProductionProcess", "ProductionProcess")
                        .WithMany("Steps")
                        .HasForeignKey("ProductionProcessId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionProcess");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStepIO", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", "Material")
                        .WithMany("ProcessStepIOs")
                        .HasForeignKey("MaterialId1");

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", null)
                        .WithMany()
                        .HasForeignKey("ProductionProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", "ProductionProcessStep")
                        .WithMany()
                        .HasForeignKey("ProductionProcessStepId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.SemiFinishedProduct", null)
                        .WithMany()
                        .HasForeignKey("SemiFinishedProductId");

                    b.HasOne("GPMS.Backend.Data.Models.Products.SemiFinishedProduct", "SemiFinishedProduct")
                        .WithMany("ProcessStepIOs")
                        .HasForeignKey("SemiFinishedProductId1");

                    b.Navigation("Material");

                    b.Navigation("ProductionProcessStep");

                    b.Navigation("SemiFinishedProduct");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.SemiFinishedProduct", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", "Product")
                        .WithMany("SemiFinishedProducts")
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.BillOfMaterial", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", "Material")
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("MaterialId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "ProductSpecification")
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductSpecification");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.Measurement", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "ProductSpecification")
                        .WithMany("Measurements")
                        .HasForeignKey("ProductSpecificationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSpecification");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Warehouses.Warehouse", "Warehouse")
                        .WithMany("Specifications")
                        .HasForeignKey("WarehouseId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.QualityStandard", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("GPMS.Backend.Data.Models.Products.Material", "Material")
                        .WithMany("QualityStandards")
                        .HasForeignKey("MaterialId1");

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "ProductSpecification")
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductSpecification");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.InspectionRequest", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", null)
                        .WithMany()
                        .HasForeignKey("ProductionSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", "ProductionSeries")
                        .WithMany("InspectionRequests")
                        .HasForeignKey("ProductionSeriesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("CreatedInspectionRequests")
                        .HasForeignKey("StaffId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("ReviewedInspectionRequests")
                        .HasForeignKey("StaffId1");

                    b.Navigation("Creator");

                    b.Navigation("ProductionSeries");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.WarehouseRequest", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("CreatedWarehouseRequests")
                        .HasForeignKey("CreatorId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", null)
                        .WithMany()
                        .HasForeignKey("ProductionRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", "ProductionRequirement")
                        .WithMany("WarehouseRequests")
                        .HasForeignKey("ProductionRequirementId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany("ReviewedWarehouseRequests")
                        .HasForeignKey("ReviewerId");

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId1");

                    b.Navigation("Creator");

                    b.Navigation("ProductionRequirement");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.FaultyProduct", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Results.InspectionRequestResult", null)
                        .WithMany()
                        .HasForeignKey("InspectionRequestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Results.InspectionRequestResult", "InspectionRequestResult")
                        .WithMany("FaultyProducts")
                        .HasForeignKey("InspectionRequestResultId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "Specification")
                        .WithMany("FaultyProducts")
                        .HasForeignKey("SpecificationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionRequestResult");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.InspectionRequestResult", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Requests.InspectionRequest", null)
                        .WithOne()
                        .HasForeignKey("GPMS.Backend.Data.Models.Results.InspectionRequestResult", "InspectionRequestId");

                    b.HasOne("GPMS.Backend.Data.Models.Requests.InspectionRequest", "InspectionRequest")
                        .WithOne("InspectionRequestResult")
                        .HasForeignKey("GPMS.Backend.Data.Models.Results.InspectionRequestResult", "InspectionRequestId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("InspectionRequest");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductFault", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Results.FaultyProduct", null)
                        .WithMany()
                        .HasForeignKey("FaultyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Results.FaultyProduct", "FaultyProduct")
                        .WithMany("ProductFaults")
                        .HasForeignKey("FaultyProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.Measurement", null)
                        .WithOne()
                        .HasForeignKey("GPMS.Backend.Data.Models.Results.ProductFault", "ProductMeasurementId");

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.Measurement", "ProductMeasurement")
                        .WithMany("ProductFaults")
                        .HasForeignKey("ProductMeasurementId1");

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", null)
                        .WithMany()
                        .HasForeignKey("ProductionProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", "ProductionProcessStep")
                        .WithMany("ProductFaults")
                        .HasForeignKey("ProductionProcessStepId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.QualityStandard", null)
                        .WithMany()
                        .HasForeignKey("QualityStandardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.QualityStandard", "QualityStandard")
                        .WithMany("ProductFaults")
                        .HasForeignKey("QualityStandardId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaultyProduct");

                    b.Navigation("ProductMeasurement");

                    b.Navigation("ProductionProcessStep");

                    b.Navigation("QualityStandard");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductionProcessStepIOResult", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStepIO", "ProductionProcessStepIO")
                        .WithMany("StepIOResults")
                        .HasForeignKey("ProductionProcessStepIOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", "ProductionProcessStepResult")
                        .WithMany("StepIOResults")
                        .HasForeignKey("ProductionProcessStepResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStepIO", null)
                        .WithMany()
                        .HasForeignKey("StepIOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", null)
                        .WithMany()
                        .HasForeignKey("StepResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionProcessStepIO");

                    b.Navigation("ProductionProcessStepResult");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Staff", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Results.InspectionRequestResult", null)
                        .WithOne()
                        .HasForeignKey("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", "InspectionRequestResultId");

                    b.HasOne("GPMS.Backend.Data.Models.Results.InspectionRequestResult", "InspectionRequestResult")
                        .WithOne("ProductionProcessStepResult")
                        .HasForeignKey("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", "InspectionRequestResultId1");

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", null)
                        .WithMany()
                        .HasForeignKey("ProductionSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", "ProductionSeries")
                        .WithMany()
                        .HasForeignKey("ProductionSeriesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("InspectionRequestResult");

                    b.Navigation("ProductionSeries");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Staff", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Account", null)
                        .WithOne("Staff")
                        .HasForeignKey("GPMS.Backend.Data.Models.Staffs.Staff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Department", null)
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Staffs.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId1");

                    b.Navigation("Account");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Warehouses.WarehouseTicket", b =>
                {
                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", null)
                        .WithMany()
                        .HasForeignKey("ProductSpecificationId");

                    b.HasOne("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", "ProductSpecification")
                        .WithMany("WarehouseTickets")
                        .HasForeignKey("ProductSpecificationId1");

                    b.HasOne("GPMS.Backend.Data.Models.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Warehouses.Warehouse", "Warehouse")
                        .WithMany("WarehouseTickets")
                        .HasForeignKey("WarehouseId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Backend.Data.Models.Requests.WarehouseRequest", null)
                        .WithOne("WarehouseTicket")
                        .HasForeignKey("GPMS.Backend.Data.Models.Warehouses.WarehouseTicket", "WarehouseRequestId");

                    b.HasOne("GPMS.Backend.Data.Models.Requests.WarehouseRequest", "WarehouseRequest")
                        .WithMany()
                        .HasForeignKey("WarehouseRequestId1");

                    b.Navigation("ProductSpecification");

                    b.Navigation("Warehouse");

                    b.Navigation("WarehouseRequest");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionEstimation", b =>
                {
                    b.Navigation("ProductionSeries");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionPlan", b =>
                {
                    b.Navigation("ChildProductionPlans");

                    b.Navigation("ProductionRequirements");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionRequirement", b =>
                {
                    b.Navigation("ProductionEstimations");

                    b.Navigation("WarehouseRequests");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.ProductionPlans.ProductionSeries", b =>
                {
                    b.Navigation("InspectionRequests");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Material", b =>
                {
                    b.Navigation("BillOfMaterials");

                    b.Navigation("ProcessStepIOs");

                    b.Navigation("QualityStandards");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Product", b =>
                {
                    b.Navigation("ProductionProcesses");

                    b.Navigation("SemiFinishedProducts");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductProductionProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStep", b =>
                {
                    b.Navigation("ProductFaults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.ProductionProcesses.ProductionProcessStepIO", b =>
                {
                    b.Navigation("StepIOResults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.SemiFinishedProduct", b =>
                {
                    b.Navigation("ProcessStepIOs");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.Measurement", b =>
                {
                    b.Navigation("ProductFaults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.ProductSpecification", b =>
                {
                    b.Navigation("FaultyProducts");

                    b.Navigation("Measurements");

                    b.Navigation("ProductionRequirements");

                    b.Navigation("WarehouseTickets");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Products.Specifications.QualityStandard", b =>
                {
                    b.Navigation("ProductFaults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.InspectionRequest", b =>
                {
                    b.Navigation("InspectionRequestResult");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Requests.WarehouseRequest", b =>
                {
                    b.Navigation("WarehouseTicket");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.FaultyProduct", b =>
                {
                    b.Navigation("ProductFaults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.InspectionRequestResult", b =>
                {
                    b.Navigation("FaultyProducts");

                    b.Navigation("ProductionProcessStepResult")
                        .IsRequired();
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Results.ProductionProcessStepResult", b =>
                {
                    b.Navigation("StepIOResults");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Account", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Department", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Staffs.Staff", b =>
                {
                    b.Navigation("CreatedInspectionRequests");

                    b.Navigation("CreatedProductionPlans");

                    b.Navigation("CreatedProducts");

                    b.Navigation("CreatedWarehouseRequests");

                    b.Navigation("ReviewedInspectionRequests");

                    b.Navigation("ReviewedProductionPlans");

                    b.Navigation("ReviewedProducts");

                    b.Navigation("ReviewedWarehouseRequests");
                });

            modelBuilder.Entity("GPMS.Backend.Data.Models.Warehouses.Warehouse", b =>
                {
                    b.Navigation("Specifications");

                    b.Navigation("WarehouseTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
