name: Trigger build and deploy on dev branch

on:
  push:
    branches: [ "dev" ]

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{secrets.JENKINS_TRIGGER_URL}}
          user: "admin"
          token: ${{secrets.TRIGGER_API_TOKEN}}
          job: "GPMS_Backend_Dev"
